services:
  - type: web
    name: controle-gastos-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "X-Requested-With, Content-Type, Authorization"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"