services:
  - type: web
    name: controle-gastos-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS, PUT, DELETE"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "X-Requested-With, Content-Type, Authorization"

